// Constants
export const GEM_STATUSES = {
  DRAFT_INTAKE: "DRAFT_INTAKE",
  TOOK_IN: "TOOK_IN",

  DRAFT_TEST_1: "DRAFT_TEST_1",
  READY_FOR_T1: "READY_FOR_T1",

  DRAFT_TEST_2: "DRAFT_TEST_2",
  READY_FOR_T2: "READY_FOR_T2",

  READY_FOR_APPROVAL: "READY_FOR_APPROVAL",
  DRAFT_APPROVAL: "DRAFT_APPROVAL",
  SUBMITTED_FOR_REPORT: "SUBMITTED_FOR_REPORT",

  REQUEST_CHANGES: "REQUEST_CHANGES",

  DONE: "DONE",
}

export const ROLES = {
  ADMIN: "ADMIN",
  TESTER: "TESTER",
  HELPER: "HELPER",
}

export const REPORT_TYPES = {
  SMALL: "small",
  MEDIUM: "medium",
  LARGE: "large",
}
