import type { User, Gem, GemReference } from "./types"

export const MOCK_USERS: User[] = [
  { id: "u1", name: "Alice Admin", role: "ADMIN", avatar: "AA" },
  { id: "u2", name: "Harry Helper", role: "HELPER", avatar: "HH" },
  { id: "u3", name: "Tom Tester (T1)", role: "TESTER", avatar: "T1" },
  { id: "u4", name: "Tim Tester (T2)", role: "TESTER", avatar: "T2" },
  { id: "u5", name: "Fiona Final", role: "FINAL_APPROVER", avatar: "FF" },
]

export const GEM_REFERENCES: GemReference[] = [
  {
    species: "Fluorite",
    variety: "Fluorite",
    riMin: 1.434,
    riMax: 1.434,
    sgMin: 3.18,
    sgMax: 3.18,
    hardness: "4",
  },
  {
    species: "Glass",
    variety: "Glass",
    riMin: 1.44,
    riMax: 1.9,
    sgMin: 2.3,
    sgMax: 4.5,
    hardness: "5-6",
  },
  {
    species: "Opal",
    variety: "Fire Opal",
    riMin: 1.435,
    riMax: 1.55,
    sgMin: 2.15,
    sgMax: 2.15,
    hardness: "5-6.5",
  },
  {
    species: "Lazurite",
    variety: "Lapis Lazuli",
    riMin: 1.5,
    riMax: 1.5,
    sgMin: 2.75,
    sgMax: 2.75,
    hardness: "5.5",
  },
  {
    species: "Feldspar",
    variety: "Amazonite",
    riMin: 1.522,
    riMax: 1.53,
    sgMin: 2.5,
    sgMax: 2.5,
    hardness: "6-6.5",
  },
  {
    species: "Spinel",
    variety: "Spinel",
    riMin: 1.718,
    riMax: 1.718,
    sgMin: 3.6,
    sgMax: 3.6,
    hardness: "8",
  },
  {
    species: "Garnet",
    variety: "Pyrope Garnet",
    riMin: 1.746,
    riMax: 1.746,
    sgMin: 3.73,
    sgMax: 3.73,
    hardness: "7-7.5",
  },
]

export const PREDEFINED_SPECIES = [
  "Natural Beryl",
  "Natural Corundum",
  "Natural Chrysoberyl",
  "Natural Spinel",
  "Natural Garnet",
  "Natural Quartz",
  "Natural Tourmaline",
  "Natural Topaz",
  "Natural Zircon",
  "Natural Peridot",
  "Natural Iolite",
  "Natural Spodumene",
  "Natural Feldspar",
  "Natural Opal",
  "Synthetic Corundum",
  "Synthetic Spinel",
  "Glass",
  "Composite",
]

export const INITIAL_GEMS: Gem[] = [
  {
    _id: "g1",
    gemId: "GEM-2024-001",
    status: "COMPLETED",
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
    emeraldWeight: 1.2,
    diamondWeight: 0.5,
    totalArticleWeight: 4.25,
    color: "Red",
    itemDescription: "One Red Stone",
    intake: { helperId: "u2", timestamp: new Date() },
    test1: {
      ri: 1.718,
      sg: 3.6,
      hardness: 8,
      selectedVariety: "Spinel",
      testerId: "u3",
      timestamp: new Date(),
    },
    test2: {
      ri: 1.718,
      sg: 3.6,
      hardness: 8,
      selectedVariety: "Spinel",
      testerId: "u4",
      timestamp: new Date(),
    },
    finalApproval: {
      ri: 1.718,
      sg: 3.6,
      hardness: 8,
      finalVariety: "Spinel",
      approverId: "u5",
      timestamp: new Date(),
    },
  },
  {
    _id: "g2",
    gemId: "GEM-2024-002",
    status: "COMPLETED",
    updatedAt: new Date(Date.now() - 100000000).toISOString(),
    emeraldWeight: 2.5,
    diamondWeight: 1.2,
    totalArticleWeight: 6.8,
    color: "Green",
    itemDescription: "One Green Stone",
    intake: { helperId: "u2", timestamp: new Date() },
    test1: {
      ri: 1.434,
      sg: 3.18,
      hardness: 4,
      selectedVariety: "Fluorite",
      testerId: "u3",
    },
    test2: { ri: 1.5, sg: 2.7, hardness: 5, selectedVariety: "Glass", testerId: "u4" },
    finalApproval: {
      ri: 1.434,
      sg: 3.18,
      hardness: 4,
      finalVariety: "Fluorite",
      approverId: "u5",
    },
  },
  {
    _id: "g3",
    gemId: "GEM-2024-003",
    status: "READY_FOR_T1",
    updatedAt: new Date().toISOString(),
    emeraldWeight: 0.8,
    diamondWeight: 0.2,
    totalArticleWeight: 2.1,
    color: "Blue",
    itemDescription: "One Blue Stone",
    intake: { helperId: "u2", timestamp: new Date() },
    test1: {},
    test2: {},
    finalApproval: {},
  },
]
