import mongoose from "mongoose"
import dotenv from "dotenv"
import User from "../models/User.js"
import GemReference from "../models/GemReference.js"
import connectDB from "../config/db.js"

dotenv.config()

const seedData = async () => {
  try {
    await connectDB()

    // Clear existing data
    await User.deleteMany({})
    await GemReference.deleteMany({})

    console.log("Cleared existing data...")

    // Create users
    const users = [
      {
        username: "admin",
        password: "password123",
        name: "Alice Admin",
        role: "ADMIN",
      },
      {
        username: "helper",
        password: "password123",
        name: "Harry Helper",
        role: "HELPER",
      },
      {
        username: "tester",
        password: "password123",
        name: "Tom Tester",
        role: "TESTER",
      },
      {
        username: "tester2",
        password: "password123",
        name: "Tim Tester",
        role: "TESTER",
      },
    ]

    const createdUsers = await User.create(users)
    console.log(`✓ Created ${createdUsers.length} users`)

    // Create gem references
    const references = [
      {
        specificGravityMin: 3.18,
        specificGravityMax: 3.18,
        species: "Fluorite",
        variety: "Fluorite",
        refractiveIndexMin: 1.434,
        refractiveIndexMax: 1.434,
        hardnessMin: 4.0,
        hardnessMax: 4.0,
      },
      {
        specificGravityMin: 2.3,
        specificGravityMax: 4.5,
        species: null,
        variety: "Glass",
        refractiveIndexMin: 1.44,
        refractiveIndexMax: 1.9,
        hardnessMin: 5.0,
        hardnessMax: 6.0,
      },
      {
        specificGravityMin: 2.15,
        specificGravityMax: 2.15,
        species: "Opal",
        variety: "Fire Opal",
        refractiveIndexMin: 1.435,
        refractiveIndexMax: 1.55,
        hardnessMin: 5.0,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 2.2,
        specificGravityMax: 2.4,
        species: "Sodalite",
        variety: "Sodalite",
        refractiveIndexMin: 1.483,
        refractiveIndexMax: 1.483,
        hardnessMin: 5.0,
        hardnessMax: 6.0,
      },
      {
        specificGravityMin: 2.7,
        specificGravityMax: 2.7,
        species: "Calcite",
        variety: "Calcite",
        refractiveIndexMin: 1.486,
        refractiveIndexMax: 1.658,
        hardnessMin: 3.0,
        hardnessMax: 3.0,
      },
      {
        specificGravityMin: 2.75,
        specificGravityMax: 2.75,
        species: "Lazurite",
        variety: "Lapis Lazuli",
        refractiveIndexMin: 1.5,
        refractiveIndexMax: 1.5,
        hardnessMin: 5.5,
        hardnessMax: 5.5,
      },
      {
        specificGravityMin: 2.4,
        specificGravityMax: 2.4,
        species: "Moldavite",
        variety: "Moldavite",
        refractiveIndexMin: 1.48,
        refractiveIndexMax: 1.48,
        hardnessMin: 5.5,
        hardnessMax: 5.5,
      },
      {
        specificGravityMin: 2.39,
        specificGravityMax: 2.39,
        species: "Petalite",
        variety: "Petalite",
        refractiveIndexMin: 1.502,
        refractiveIndexMax: 1.518,
        hardnessMin: 6.0,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 2.5,
        specificGravityMax: 2.5,
        species: "Feldspar",
        variety: "Moonstone Sanidine (Orthoclase)",
        refractiveIndexMin: 1.518,
        refractiveIndexMax: 1.526,
        hardnessMin: 6.0,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 2.5,
        specificGravityMax: 2.5,
        species: "Feldspar",
        variety: "Amazonite",
        refractiveIndexMin: 1.522,
        refractiveIndexMax: 1.53,
        hardnessMin: 6.0,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 2.66,
        specificGravityMax: 2.66,
        species: null,
        variety: "Peral",
        refractiveIndexMin: 1.53,
        refractiveIndexMax: 1.69,
        hardnessMin: 2.5,
        hardnessMax: 4.5,
      },
      {
        specificGravityMin: 2.65,
        specificGravityMax: 2.65,
        species: "Feldspar",
        variety: "Aventurine Feldspar",
        refractiveIndexMin: 1.532,
        refractiveIndexMax: 1.542,
        hardnessMin: 6.0,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 2.6,
        specificGravityMax: 2.6,
        species: "Chalcedony",
        variety: "Chalcedony",
        refractiveIndexMin: 1.53,
        refractiveIndexMax: 1.539,
        hardnessMin: 6.5,
        hardnessMax: 7.0,
      },
      {
        specificGravityMin: 1.08,
        specificGravityMax: 1.08,
        species: "Amber",
        variety: "Ambar",
        refractiveIndexMin: 1.54,
        refractiveIndexMax: 1.54,
        hardnessMin: 2.0,
        hardnessMax: 2.5,
      },
      {
        specificGravityMin: 1.85,
        specificGravityMax: 1.85,
        species: "Organic",
        variety: "Ivory",
        refractiveIndexMin: 1.54,
        refractiveIndexMax: 1.54,
        hardnessMin: 2.25,
        hardnessMax: 2.75,
      },
      {
        specificGravityMin: 2.61,
        specificGravityMax: 2.61,
        species: "Cordierite",
        variety: "Iolite",
        refractiveIndexMin: 1.542,
        refractiveIndexMax: 1.551,
        hardnessMin: 7.0,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 2.65,
        specificGravityMax: 2.65,
        species: "Quartz",
        variety: "Quartz",
        refractiveIndexMin: 1.544,
        refractiveIndexMax: 1.553,
        hardnessMin: 7.0,
        hardnessMax: 7.0,
      },
      {
        specificGravityMin: 2.64,
        specificGravityMax: 2.64,
        species: "Scapolite",
        variety: "Scapolite",
        refractiveIndexMin: 1.544,
        refractiveIndexMax: 1.56,
        hardnessMin: 3.5,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 2.85,
        specificGravityMax: 2.85,
        species: "Beryllonite",
        variety: "Beryllonite",
        refractiveIndexMin: 1.552,
        refractiveIndexMax: 1.562,
        hardnessMin: 5.5,
        hardnessMax: 6.0,
      },
      {
        specificGravityMin: 2.35,
        specificGravityMax: 2.35,
        species: "Hambergite",
        variety: "Hambergite",
        refractiveIndexMin: 1.555,
        refractiveIndexMax: 1.626,
        hardnessMin: 7.5,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 2.7,
        specificGravityMax: 2.7,
        species: "Feldspar",
        variety: "Labradorite",
        refractiveIndexMin: 1.56,
        refractiveIndexMax: 1.57,
        hardnessMin: 6.0,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 2.65,
        specificGravityMax: 2.65,
        species: "Beryl (synthetic)",
        variety: "Emarald (Syn)",
        refractiveIndexMin: 1.563,
        refractiveIndexMax: 1.667,
        hardnessMin: 7.5,
        hardnessMax: 8.0,
      },
      {
        specificGravityMin: 2.71,
        specificGravityMax: 2.71,
        species: "Beryl",
        variety: "Aquamarine",
        refractiveIndexMin: 1.577,
        refractiveIndexMax: 1.583,
        hardnessMin: 7.5,
        hardnessMax: 8.0,
      },
      {
        specificGravityMin: 2.71,
        specificGravityMax: 2.71,
        species: "Beryl",
        variety: "Emarald (N)",
        refractiveIndexMin: 1.565,
        refractiveIndexMax: 1.575,
        hardnessMin: 5.0,
        hardnessMax: 8.0,
      },
      {
        specificGravityMin: 2.7,
        specificGravityMax: 2.7,
        species: "Beryl",
        variety: "Heliodor",
        refractiveIndexMin: 1.57,
        refractiveIndexMax: 1.58,
        hardnessMin: 2.5,
        hardnessMax: 8.0,
      },
      {
        specificGravityMin: 3.68,
        specificGravityMax: 3.68,
        species: "Beryl",
        variety: "Morganite",
        refractiveIndexMin: 1.58,
        refractiveIndexMax: 1.6,
        hardnessMin: 3.5,
        hardnessMax: 4.5,
      },
      {
        specificGravityMin: 2.82,
        specificGravityMax: 2.82,
        species: "Rhodochrosite",
        variety: "Rhodochrosite",
        refractiveIndexMin: 1.685,
        refractiveIndexMax: 1.694,
        hardnessMin: 7.5,
        hardnessMax: 8.0,
      },
      {
        specificGravityMin: 2.94,
        specificGravityMax: 2.94,
        species: "Brazilianite",
        variety: "Brazilianite",
        refractiveIndexMin: 1.602,
        refractiveIndexMax: 1.621,
        hardnessMin: 5.5,
        hardnessMax: 5.5,
      },
      {
        specificGravityMin: 2.95,
        specificGravityMax: 2.95,
        species: "Jade",
        variety: "Nephrite",
        refractiveIndexMin: 1.606,
        refractiveIndexMax: 1.632,
        hardnessMin: 6.0,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 2.76,
        specificGravityMax: 2.76,
        species: "Turquoise",
        variety: "Turquoise",
        refractiveIndexMin: 1.61,
        refractiveIndexMax: 1.65,
        hardnessMin: 5.0,
        hardnessMax: 6.0,
      },
      {
        specificGravityMin: 3.0,
        specificGravityMax: 3.0,
        species: "Amblygonite",
        variety: "Amblygonite",
        refractiveIndexMin: 1.612,
        refractiveIndexMax: 1.636,
        hardnessMin: 6.0,
        hardnessMax: 6.0,
      },
      {
        specificGravityMin: 2.88,
        specificGravityMax: 2.88,
        species: "Prehnite",
        variety: "Prehnite",
        refractiveIndexMin: 1.618,
        refractiveIndexMax: 1.648,
        hardnessMin: 6.0,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 3.53,
        specificGravityMax: 3.53,
        species: "Topaz",
        variety: "Topaz",
        refractiveIndexMin: 1.609,
        refractiveIndexMax: 1.627,
        hardnessMin: 8.0,
        hardnessMax: 8.0,
      },
      {
        specificGravityMin: 4.1,
        specificGravityMax: 4.1,
        species: "Smithsonite",
        variety: "Smithsonite",
        refractiveIndexMin: 1.621,
        refractiveIndexMax: 1.849,
        hardnessMin: 5.0,
        hardnessMax: 5.5,
      },
      {
        specificGravityMin: 3.06,
        specificGravityMax: 3.06,
        species: "Tourmaline group",
        variety: "Tourmaline",
        refractiveIndexMin: 1.624,
        refractiveIndexMax: 1.644,
        hardnessMin: 7.0,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 3.0,
        specificGravityMax: 3.0,
        species: "Danburite",
        variety: "Danburite",
        refractiveIndexMin: 1.63,
        refractiveIndexMax: 1.636,
        hardnessMin: 7.0,
        hardnessMax: 7.0,
      },
      {
        specificGravityMin: 3.17,
        specificGravityMax: 3.17,
        species: "Andalusite",
        variety: "Andalusite",
        refractiveIndexMin: 1.634,
        refractiveIndexMax: 1.643,
        hardnessMin: 7.5,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 3.17,
        specificGravityMax: 3.17,
        species: "Apatite",
        variety: "Apatite",
        refractiveIndexMin: 1.642,
        refractiveIndexMax: 1.646,
        hardnessMin: 5.0,
        hardnessMax: 5.0,
      },
      {
        specificGravityMin: 2.95,
        specificGravityMax: 2.95,
        species: "Phenakite",
        variety: "Phenakite",
        refractiveIndexMin: 1.654,
        refractiveIndexMax: 1.67,
        hardnessMin: 7.5,
        hardnessMax: 8.0,
      },
      {
        specificGravityMin: 3.1,
        specificGravityMax: 3.1,
        species: "Euclase",
        variety: "Euclase",
        refractiveIndexMin: 1.654,
        refractiveIndexMax: 1.673,
        hardnessMin: 7.5,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 3.34,
        specificGravityMax: 3.34,
        species: "Olivine",
        variety: "Peridot",
        refractiveIndexMin: 1.654,
        refractiveIndexMax: 1.69,
        hardnessMin: 6.5,
        hardnessMax: 7.0,
      },
      {
        specificGravityMin: 3.3,
        specificGravityMax: 3.3,
        species: "Dioptase",
        variety: "Dioptase",
        refractiveIndexMin: 1.655,
        refractiveIndexMax: 1.708,
        hardnessMin: 5.0,
        hardnessMax: 5.0,
      },
      {
        specificGravityMin: 3.25,
        specificGravityMax: 3.25,
        species: "Enstatite",
        variety: "Enstatite",
        refractiveIndexMin: 1.658,
        refractiveIndexMax: 1.673,
        hardnessMin: 5.5,
        hardnessMax: 5.5,
      },
      {
        specificGravityMin: 3.24,
        specificGravityMax: 3.24,
        species: "Sillimanite",
        variety: "Sillimanite",
        refractiveIndexMin: 1.659,
        refractiveIndexMax: 1.68,
        hardnessMin: 6.0,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 3.18,
        specificGravityMax: 3.18,
        species: "Spodumene",
        variety: "Spodumene (Kunzite)",
        refractiveIndexMin: 1.66,
        refractiveIndexMax: 1.676,
        hardnessMin: 6.0,
        hardnessMax: 7.0,
      },
      {
        specificGravityMin: 3.34,
        specificGravityMax: 3.34,
        species: "Jade",
        variety: "Jadeite",
        refractiveIndexMin: 1.66,
        refractiveIndexMax: 1.68,
        hardnessMin: 6.5,
        hardnessMax: 7.0,
      },
      {
        specificGravityMin: 3.95,
        specificGravityMax: 3.95,
        species: "Malachite",
        variety: "Malachite",
        refractiveIndexMin: 1.66,
        refractiveIndexMax: 1.91,
        hardnessMin: 3.5,
        hardnessMax: 4.0,
      },
      {
        specificGravityMin: 3.32,
        specificGravityMax: 3.32,
        species: "Kornerupine",
        variety: "Komerupine",
        refractiveIndexMin: 1.665,
        refractiveIndexMax: 1.682,
        hardnessMin: 6.5,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 3.48,
        specificGravityMax: 3.48,
        species: "Sinhalite",
        variety: "Sinhalite",
        refractiveIndexMin: 1.668,
        refractiveIndexMax: 1.707,
        hardnessMin: 6.0,
        hardnessMax: 7.0,
      },
      {
        specificGravityMin: 3.29,
        specificGravityMax: 3.29,
        species: "Pyroxene",
        variety: "Diopside",
        refractiveIndexMin: 1.675,
        refractiveIndexMax: 1.701,
        hardnessMin: 5.0,
        hardnessMax: 6.0,
      },
      {
        specificGravityMin: 3.29,
        specificGravityMax: 3.29,
        species: "Axinite",
        variety: "Axinite",
        refractiveIndexMin: 1.678,
        refractiveIndexMax: 1.688,
        hardnessMin: 6.5,
        hardnessMax: 7.0,
      },
      {
        specificGravityMin: 3.3,
        specificGravityMax: 3.3,
        species: "Epidote",
        variety: "Zoisite (Tanzanite)",
        refractiveIndexMin: 1.69,
        refractiveIndexMax: 1.706,
        hardnessMin: 6.7,
        hardnessMax: 6.7,
      },
      {
        specificGravityMin: 3.4,
        specificGravityMax: 3.4,
        species: "Idocrase (Vesuvianite)",
        variety: "Idocrase",
        refractiveIndexMin: 1.713,
        refractiveIndexMax: 1.718,
        hardnessMin: 6.5,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 3.45,
        specificGravityMax: 3.45,
        species: "Enstatite",
        variety: "Hypersthene",
        refractiveIndexMin: 1.715,
        refractiveIndexMax: 1.731,
        hardnessMin: 5.0,
        hardnessMax: 6.0,
      },
      {
        specificGravityMin: 3.62,
        specificGravityMax: 3.62,
        species: "Kyanite",
        variety: "Kyanite",
        refractiveIndexMin: 1.716,
        refractiveIndexMax: 1.731,
        hardnessMin: 4.0,
        hardnessMax: 6.0,
      },
      {
        specificGravityMin: 3.6,
        specificGravityMax: 3.6,
        species: "Spinel",
        variety: "Spinel",
        refractiveIndexMin: 1.718,
        refractiveIndexMax: 1.718,
        hardnessMin: 8.0,
        hardnessMax: 8.0,
      },
      {
        specificGravityMin: 3.61,
        specificGravityMax: 3.61,
        species: "Taaffeite: Taaffeite",
        variety: "Taaffeite",
        refractiveIndexMin: 1.719,
        refractiveIndexMax: 1.723,
        hardnessMin: 8.0,
        hardnessMax: 8.0,
      },
      {
        specificGravityMin: 3.6,
        specificGravityMax: 3.6,
        species: "Spinel (Syn)",
        variety: "Spinel (Syn)",
        refractiveIndexMin: 1.73,
        refractiveIndexMax: 1.73,
        hardnessMin: 8.0,
        hardnessMax: 8.0,
      },
      {
        specificGravityMin: 3.4,
        specificGravityMax: 3.4,
        species: "Rhodonite",
        variety: "Rhodonite",
        refractiveIndexMin: 1.733,
        refractiveIndexMax: 1.744,
        hardnessMin: 5.5,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 3.4,
        specificGravityMax: 3.4,
        species: "Epidote",
        variety: "Epidote",
        refractiveIndexMin: 1.733,
        refractiveIndexMax: 1.768,
        hardnessMin: 6.0,
        hardnessMax: 7.0,
      },
      {
        specificGravityMin: 3.61,
        specificGravityMax: 3.61,
        species: "Garnet",
        variety: "Grossular Granet",
        refractiveIndexMin: 1.734,
        refractiveIndexMax: 1.734,
        hardnessMin: 7.0,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 3.61,
        specificGravityMax: 3.61,
        species: "Garnet",
        variety: "Hessonite Garnet",
        refractiveIndexMin: 1.74,
        refractiveIndexMax: 1.74,
        hardnessMin: 7.0,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 3.73,
        specificGravityMax: 3.73,
        species: "Garnet",
        variety: "Pyrope Garnet",
        refractiveIndexMin: 1.746,
        refractiveIndexMax: 1.746,
        hardnessMin: 7.0,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 3.73,
        specificGravityMax: 3.73,
        species: "Chrysoberyl",
        variety: "Chrysoberyl",
        refractiveIndexMin: 1.746,
        refractiveIndexMax: 1.755,
        hardnessMin: 8.5,
        hardnessMax: 8.5,
      },
      {
        specificGravityMin: 3.73,
        specificGravityMax: 3.73,
        species: "Chrysoberyl",
        variety: "Alexandrite",
        refractiveIndexMin: 1.746,
        refractiveIndexMax: 1.757,
        hardnessMin: 8.5,
        hardnessMax: 8.5,
      },
      {
        specificGravityMin: 3.64,
        specificGravityMax: 3.64,
        species: "Benitoite",
        variety: "Benitoite",
        refractiveIndexMin: 1.757,
        refractiveIndexMax: 1.804,
        hardnessMin: 6.0,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 3.84,
        specificGravityMax: 3.84,
        species: "Garnet",
        variety: "Rhodolite",
        refractiveIndexMin: 1.76,
        refractiveIndexMax: 1.76,
        hardnessMin: 7.0,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 3.99,
        specificGravityMax: 3.99,
        species: "Corundum",
        variety: "Sapphire",
        refractiveIndexMin: 1.762,
        refractiveIndexMax: 1.77,
        hardnessMin: 9.0,
        hardnessMax: 9.0,
      },
      {
        specificGravityMin: 3.99,
        specificGravityMax: 3.99,
        species: "Corundum",
        variety: "Ruby",
        refractiveIndexMin: 1.762,
        refractiveIndexMax: 1.77,
        hardnessMin: 9.0,
        hardnessMax: 9.0,
      },
      {
        specificGravityMin: 4.05,
        specificGravityMax: 4.05,
        species: "Garnet",
        variety: "Almandine Garnet",
        refractiveIndexMin: 1.79,
        refractiveIndexMax: 1.79,
        hardnessMin: 7.5,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 3.77,
        specificGravityMax: 3.77,
        species: "Garnet",
        variety: "Uvarovite",
        refractiveIndexMin: 1.87,
        refractiveIndexMax: 1.87,
        hardnessMin: 7.5,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 4.15,
        specificGravityMax: 4.15,
        species: "Garnet",
        variety: "Spessartite",
        refractiveIndexMin: 1.81,
        refractiveIndexMax: 1.81,
        hardnessMin: 7.0,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 3.82,
        specificGravityMax: 3.82,
        species: "Garnet",
        variety: "Demantoid",
        refractiveIndexMin: 1.88,
        refractiveIndexMax: 1.88,
        hardnessMin: 6.5,
        hardnessMax: 7.0,
      },
      {
        specificGravityMin: 4.0,
        specificGravityMax: 4.0,
        species: "Zircon",
        variety: "Zircon (low)",
        refractiveIndexMin: 1.81,
        refractiveIndexMax: 1.815,
        hardnessMin: 6.5,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 4.32,
        specificGravityMax: 4.32,
        species: "Zircon",
        variety: "Zircon (Intermediate)",
        refractiveIndexMin: 1.875,
        refractiveIndexMax: 1.905,
        hardnessMin: 7.0,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 5.1,
        specificGravityMax: 5.1,
        species: "Scheelite",
        variety: "Scheelite",
        refractiveIndexMin: 1.918,
        refractiveIndexMax: 1.934,
        hardnessMin: 4.5,
        hardnessMax: 5.0,
      },
      {
        specificGravityMin: 4.7,
        specificGravityMax: 4.7,
        species: "Zircon",
        variety: "Zircon (High)",
        refractiveIndexMin: 1.925,
        refractiveIndexMax: 1.984,
        hardnessMin: 7.0,
        hardnessMax: 7.5,
      },
      {
        specificGravityMin: 3.45,
        specificGravityMax: 3.45,
        species: "Serendibite",
        variety: "Serendibite",
        refractiveIndexMin: 1.697,
        refractiveIndexMax: 1.702,
        hardnessMin: 6.5,
        hardnessMax: 6.5,
      },
      {
        specificGravityMin: 5.6,
        specificGravityMax: 6.0,
        species: null,
        variety: "Cubic Zirconia",
        refractiveIndexMin: 2.17,
        refractiveIndexMax: 2.17,
        hardnessMin: 8.0,
        hardnessMax: 8.5,
      },
      {
        specificGravityMin: 3.52,
        specificGravityMax: 3.52,
        species: "Diamond",
        variety: "Diamond",
        refractiveIndexMin: 2.42,
        refractiveIndexMax: 2.42,
        hardnessMin: 10.0,
        hardnessMax: 10.0,
      },
    ]

    const createdReferences = await GemReference.create(references)
    console.log(`✓ Created ${createdReferences.length} gem references`)

    console.log("\n✅ Database seeded successfully!")
    console.log("\nLogin credentials:")
    console.log("  Admin:    admin / password123")
    console.log("  Helper:   helper / password123")
    console.log("  Tester:   tester / password123")
    console.log("  Approver: approver / password123")

    process.exit(0)
  } catch (error) {
    console.error("❌ Error seeding database:", error)
    process.exit(1)
  }
}

seedData()
